FROM node:23.10.0-alpine3.21 AS builder

# Set the working directory in the container
WORKDIR /app

# Install Nx globally via npm (you can also use yarn if preferred)
#RUN npm install -g nx@latest

# Copy package.json and package-lock.json/yarn.lock to the working directory
COPY package*.json ./
COPY .npmrc ./

# Install dependencies
RUN yarn

# Copy the rest of the application code
COPY . .

RUN yarn build-storybook

FROM versana.azurecr.io/vendor_images/python:3.13.5-bullseye
WORKDIR /app
ARG CONTEXT_PATH
COPY --from=builder /app/storybook_static ${CONTEXT_PATH}
EXPOSE 8081
CMD python -m http.server 8081
